version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    # environment:
    #   - DATABASE_URL=postgresql://postgres:password@db:5432/fastapi_db
    #   - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=auragold
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7

volumes:
  pg_data:
