"""Update: banks foreign key

Revision ID: 120ba428c0a1
Revises: d841fd7b9ea7
Create Date: 2023-08-18 13:33:52.582745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120ba428c0a1'
down_revision = 'd841fd7b9ea7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mandates_bank_id_fkey', 'mandates', type_='foreignkey')
    op.create_foreign_key(None, 'mandates', 'user_banks', ['bank_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mandates', type_='foreignkey')
    op.create_foreign_key('mandates_bank_id_fkey', 'mandates', 'users', ['bank_id'], ['id'])
    # ### end Alembic commands ###
