"""Create transaction, wallet, invoice table

Revision ID: 2e83d9c37f4a
Revises: 47784865e98b
Create Date: 2023-07-25 00:38:03.691722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e83d9c37f4a'
down_revision = '47784865e98b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('download_url', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_downloaded', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('wallets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qty_g', sa.Float(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qty_g', sa.Float(), nullable=False),
    sa.Column('value_wo_gst_rs', sa.Float(), nullable=False),
    sa.Column('gst_rs', sa.Float(), nullable=False),
    sa.Column('total_value_rs', sa.Float(), nullable=False),
    sa.Column('txn_status', sa.String(), nullable=False),
    sa.Column('txn_type', sa.String(), nullable=False),
    sa.Column('txn_subtype', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('show_in_app', sa.Boolean(), nullable=False),
    sa.Column('attached_coupon_code', sa.String(), nullable=True),
    sa.Column('discount_rs', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_txn_status'), 'transactions', ['txn_status'], unique=False)
    op.create_index(op.f('ix_transactions_txn_subtype'), 'transactions', ['txn_subtype'], unique=False)
    op.create_index(op.f('ix_transactions_txn_type'), 'transactions', ['txn_type'], unique=False)
    op.create_index(op.f('ix_transactions_uuid'), 'transactions', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_uuid'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_txn_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_txn_subtype'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_txn_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
