"""bug fix on wallet model

Revision ID: 366e0b4e2eb8
Revises: 68f6d4736539
Create Date: 2023-07-25 13:57:23.745548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366e0b4e2eb8'
down_revision = '68f6d4736539'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
