"""Create: user kyc details table

Revision ID: 397c3c5bd636
Revises: a1fc6f127523
Create Date: 2023-08-07 19:38:29.756408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '397c3c5bd636'
down_revision = 'a1fc6f127523'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_kyc_detailses',
    sa.Column('kyc_verified_on', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('kyc_verified_by', sa.String(), nullable=False),
    sa.Column('kyc_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kyc_number', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kyc_request_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_kyc_detailses_id'), 'user_kyc_detailses', ['id'], unique=False)
    op.create_index(op.f('ix_user_kyc_detailses_kyc_number'), 'user_kyc_detailses', ['kyc_number'], unique=False)
    op.add_column('users', sa.Column('kyc_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kyc_verified')
    op.drop_index(op.f('ix_user_kyc_detailses_kyc_number'), table_name='user_kyc_detailses')
    op.drop_index(op.f('ix_user_kyc_detailses_id'), table_name='user_kyc_detailses')
    op.drop_table('user_kyc_detailses')
    # ### end Alembic commands ###
