"""Create 24K GOLD price table

Revision ID: 47784865e98b
Revises: 2f676c45cf7f
Create Date: 2023-07-12 18:45:15.720835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47784865e98b'
down_revision = '2f676c45cf7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold24_prices',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('price_w_gst', sa.Float(), nullable=False),
    sa.Column('price_wo_gst', sa.Float(), nullable=False),
    sa.Column('applied_gst', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gold24_prices_id'), 'gold24_prices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gold24_prices_id'), table_name='gold24_prices')
    op.drop_table('gold24_prices')
    # ### end Alembic commands ###
