"""Add column on Gold24K prices

Revision ID: 68f6d4736539
Revises: 2e83d9c37f4a
Create Date: 2023-07-25 02:02:13.340239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f6d4736539'
down_revision = '2e83d9c37f4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gold24_prices', sa.Column('aura_buy_price', sa.Float(), nullable=True))
    op.add_column('gold24_prices', sa.Column('aura_sell_price', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('rate_per_g_wo_gst', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'rate_per_g_wo_gst')
    op.drop_column('gold24_prices', 'aura_sell_price')
    op.drop_column('gold24_prices', 'aura_buy_price')
    # ### end Alembic commands ###
