"""Add: payment mode column

Revision ID: 6c7a35a68283
Revises: 192c56b60f20
Create Date: 2023-08-03 17:55:02.628221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7a35a68283'
down_revision = '192c56b60f20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payment_mode')
    # ### end Alembic commands ###
