"""Update: notification_id col

Revision ID: 8d52bdae41a3
Revises: fedf66973040
Create Date: 2023-09-02 02:30:18.182542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d52bdae41a3'
down_revision = 'fedf66973040'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mandate_notifications_mandate_transaction_id_fkey', 'mandate_notifications', type_='foreignkey')
    op.drop_column('mandate_notifications', 'mandate_transaction_id')
    op.add_column('mandate_transactions', sa.Column('notification_id', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'mandate_transactions', ['txn_no'])
    op.create_foreign_key(None, 'mandate_transactions', 'mandate_notifications', ['notification_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mandate_transactions', type_='foreignkey')
    op.drop_constraint(None, 'mandate_transactions', type_='unique')
    op.drop_column('mandate_transactions', 'notification_id')
    op.add_column('mandate_notifications', sa.Column('mandate_transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('mandate_notifications_mandate_transaction_id_fkey', 'mandate_notifications', 'mandate_transactions', ['mandate_transaction_id'], ['id'])
    # ### end Alembic commands ###
