"""Update: add columns in mandate transaction

Revision ID: 96b44b2e66c6
Revises: caec850e1384
Create Date: 2023-08-29 09:53:43.239477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b44b2e66c6'
down_revision = 'caec850e1384'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mandate_transactions', sa.Column('execution_ref', sa.String(), nullable=True))
    op.add_column('mandate_transactions', sa.Column('txn_no', sa.String(), nullable=False))
    op.add_column('mandate_transactions', sa.Column('bank_rrn', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mandate_transactions', 'bank_rrn')
    op.drop_column('mandate_transactions', 'txn_no')
    op.drop_column('mandate_transactions', 'execution_ref')
    # ### end Alembic commands ###
