"""Update: update json column

Revision ID: a62253907a20
Revises: eaf81eb4abbc
Create Date: 2023-08-18 15:08:05.688687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a62253907a20'
down_revision = 'eaf81eb4abbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'meta_data')
    # ### end Alembic commands ###
