"""Add: vendor logging table

Revision ID: bae74ecd244a
Revises: 0042bf032529
Create Date: 2023-08-28 14:22:09.819990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bae74ecd244a'
down_revision = '0042bf032529'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_api_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('encrypted_request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('headers', sa.String(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('encrypted_response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Kolkata', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_api_logs_id'), 'vendor_api_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_api_logs_id'), table_name='vendor_api_logs')
    op.drop_table('vendor_api_logs')
    # ### end Alembic commands ###
