"""Add: banks model

Revision ID: d841fd7b9ea7
Revises: 37007784992c
Create Date: 2023-08-18 13:31:10.221030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd841fd7b9ea7'
down_revision = '37007784992c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_banks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('ifsc_code', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('account_holder_name', sa.String(), nullable=False),
    sa.Column('vpa', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_banks_id'), 'user_banks', ['id'], unique=False)
    op.add_column('mandates', sa.Column('bank_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mandates', 'users', ['bank_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mandates', type_='foreignkey')
    op.drop_column('mandates', 'bank_id')
    op.drop_index(op.f('ix_user_banks_id'), table_name='user_banks')
    op.drop_table('user_banks')
    # ### end Alembic commands ###
