"""Update: add columns onmandate

Revision ID: e5409541f943
Revises: fe60f0741e29
Create Date: 2023-08-24 00:30:59.675617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5409541f943'
down_revision = 'fe60f0741e29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mandate_notifications', sa.Column('seq_no', sa.String(), nullable=True))
    op.add_column('mandate_notifications', sa.Column('expected_execution_date', sa.String(), nullable=False))
    op.add_column('mandates', sa.Column('last_success_notify_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mandates', sa.Column('last_success_execution_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mandates', 'last_success_execution_date')
    op.drop_column('mandates', 'last_success_notify_date')
    op.drop_column('mandate_notifications', 'expected_execution_date')
    op.drop_column('mandate_notifications', 'seq_no')
    # ### end Alembic commands ###
