"""Update: created_updated_all_tables

Revision ID: fe60f0741e29
Revises: 6571e58dd4b2
Create Date: 2023-08-23 18:12:19.862460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fe60f0741e29"
down_revision = "6571e58dd4b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gold24_prices",
        "created_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "gold24_prices",
        "updated_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )

    op.alter_column(
        "invoices",
        "created_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "invoices",
        "updated_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )

    op.alter_column(
        "mandates",
        "created_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "mandates",
        "updated_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )

    op.alter_column(
        "partners",
        "created_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "partners",
        "updated_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )

    op.alter_column(
        "transactions",
        "created_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "transactions",
        "updated_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )

    op.alter_column(
        "user_banks",
        "created_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "user_banks",
        "updated_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )

    op.alter_column(
        "user_kyc_details",
        "created_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "user_kyc_details",
        "updated_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )

    op.alter_column(
        "user_metas",
        "created_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "user_metas",
        "updated_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )

    op.alter_column(
        "users",
        "created_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "users",
        "updated_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )

    op.alter_column(
        "wallets",
        "created_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "wallets",
        "updated_at",
        server_default=sa.text("timezone('Asia/Kolkata', CURRENT_TIMESTAMP)"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
